# -*- coding: utf-8 -*-
"""nrk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ueJlJtUjNbnyBLtvVnIGcQY_rfSnQeO
"""

import numpy as np
import pandas as pd
df=pd.read_csv('/content/diabetes.csv')
df

df.head()

df.tail()

df.columns

df.info()

df.isna().sum()

x=df.iloc[:,:-1].values
x

y=df.iloc[:,-1].values
y

y.ndim

x.ndim

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

x_test

x_train

y_train

y_test

x_test.shape

x_train.shape

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier()
nav=GaussianNB()
sup=SVC()
lst=[knn,nav,sup]
lst

for i in lst:
  print(i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("confusion_matrix",confusion_matrix(y_pred,y_test))
  print("......................................")
  print("accuracy_score",accuracy_score(y_pred,y_test))
  print("........................................")
  print("classification_report",classification_report(y_pred,y_test))

print(i.predict([[10,101,76,48,180,32.9,0.171,63]]))

